env:
  browser: true
  commonjs: true
  es6: true
extends: 'eslint:recommended'
parserOptions:
  ecmaFeatures:
    experimentalObjectRestSpread: true
    jsx: true
  sourceType: module
plugins:
  - react
settings:
    react:
      pragma: React
      version: 0.14.7
rules:
  indent:
    - error
    - 4
  linebreak-style:
    - error
    - unix
  quotes:
    - error
    - single
  semi:
    - error
    - never
  react/jsx-uses-vars:
    - error
  react/jsx-uses-react:
    - error
  react/react-in-jsx-scope:
    - error
  strict:
    - off
parser: babel-eslint
